### ISSUE TITLE
Feature Request: Support Initial Start Time For Recurring Backup/Optimize Tasks

### ISSUE THREAD

**Issue by Ciscog33k** [sethgoldin/davinci-resolve-postgresql-workflow-tools#18]
I would love to see a change to the install that allows specification of time of when to begin the <interval> count.  In my use case, I want a daily backup.  However, since I would install it during work hours, the interval should commence from that point if my understanding is correct.  Meaning our DB will be locked for a good while while the dump is underway when the 24h window cycles.  I would like this to configurable so it can commence the job at night, where it won't affect availability or latency.

I'm open to alternatives, as long as it gets the same result.  While I could do it with a cronjob, but I'd rather use your solution if it can support it.

**Comment by sethgoldin** [comment]
This shouldn't be too difficult to do, though it might take me some time for me to build this all out with feature parity across Mac and Linux.

It'll probably be faster, if you want this sooner rather than later, if I were just to give you a line or two of code with instructions to modify your own copy of the script you already have downloaded. A few questions for you:

1. Which platform are you using: Mac or Linux?
2. Do you know how large your database actually is? You [can check within the psql shell](https://stackoverflow.com/questions/14346371/postgresql-find-total-disk-space-used-by-a-database).
3. What exact time of day would you actually want each backup and optimize tasks to begin?
4. Do you have a sense of how long each backup or optimize task actually takes?

The reason I'm asking about the size and the time duration of the tasks is because I keep all my databases as small as possible, and the operations take hardly any time at all on my system--literally just a few seconds. So, we should get a sense for how long each task actually takes with your larger databases so that we can stagger the two different operations accordingly.

We could also try and just run each kind of task once and just see how long each kind of operation takes, just as a kind of benchmark, so that we can tailor the script accordingly.

**Comment by sethgoldin** [comment]
Note to self: on Linux, this should be as simple as changing the [systemd timer](https://www.freedesktop.org/software/systemd/man/systemd.timer.html) to a "realtime" timer, i.e. using an `OnCalendar=` option, and just specifying the time with the right [syntax](https://www.freedesktop.org/software/systemd/man/systemd.time.html).

If @Ciscog33k is on a Mac, I'll have to do some additional research about `launchd`.

**Comment by sethgoldin** [comment]
Without additional feedback from @Ciscog33k, I won’t be able to address.

**Comment by Ciscog33k** [comment]
So sorry for that delay!  Was head down on projects.  You know how this industry is,

1) Current deployments are macOS High/Sierra

2)  Started 2 weeks back, we're up to 606MB currently.  (~120MB per .backup)

3) If I had total freedom of choice, I'd set something like 3/4AM.  Since we work late some nights.

4a) Direct backup script execution: 01:38 with current DB size.

4b) Direct optimize script execution: 00:14 with current DB size.


BTW: The logs created in ~/DaVinci-Resolve-PostgreSQL-Workflow-Tools/logs could really benefit from timestamps.  (Perhaps a start and stop too?)

**Comment by sethgoldin** [comment]
Probably can't get to this myself any time soon, but it would make for a reasonable pull request that I'd merge.

If you want to go modify the heredoc in your own script, you could specify the timed job with your own parameters with this syntax: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/ScheduledJobs.html#//apple_ref/doc/uid/10000172i-CH1-SW1

So, in `macos-automate-workflow.sh`, you'd replace lines 131-132 with this, and fill in with your own parameters. Ditto for 148-149.

```
<key>StartCalendarInterval</key>
    <dict>
        <key>Day</key>
        <integer>11</integer>
        <key>Hour</key>
        <integer>0</integer>
        <key>Minute</key>
        <integer>0</integer>
        <key>Month</key>
        <integer>7</integer>
        <key>Weekday</key>
        <integer>0</integer>
```

You could also comment out lines 23 through 29 and/or 36 through 42, since those won't matter anymore.

**Comment by sethgoldin** [comment]
By the way, the logs already have timestamps--they show when databases were backed up or optimized, when those actions are actually completed. You could maybe copy line 111 and modify it to reflect the "start" of an action by putting it between 108 and 109. Ditto for taking copying and modifying 85 up to before 82.

**Comment by sethgoldin** [comment]
Don't have the time right now to modify the codebase, but after having offered valid suggestions for the personal workflow, I'm going to go ahead and close this.
