### ISSUE TITLE
Database optimization - how to request never?

### ISSUE THREAD

**Issue by cmcclen** [sethgoldin/davinci-resolve-postgresql-workflow-tools#40]
Tried "0D" as the answer. Is it possible to not elect database optimization without modifying your otherwise excellent work?

**Comment by sethgoldin** [comment]
You should optimize regularly. 😆

But if you don't want to do that, you could totally comment out the relevant lines in the installation script with the optimizing variable, the optimizing heredoc, and the optimizing systemd unit.

The comments should make this easy enough to do, but otherwise, hit me up for some bespoke consulting: https://www.sethgoldin.com/courses/definitive-guide-postgresql-davinci-resolve#contact

**Comment by cmcclen** [comment]
Yes, you are right about optimizing and better to automate than rely on user at workstation.
